### PR TITLE
Add zcomet

### PR DESCRIPTION
**Pull request by agkozak**
# Added the `zcomet` plugin manager

# I added the [`zcomet`](https://github.com/agkozak/zcomet) plugin manager to the Frameworks section.

- [ ] A link to an external resource like a blog post
- [x] Add/remove/update a link to a framework
- [ ] Add/remove/update a link to a plugin
- [ ] Add/remove/update a link to a tab completion
- [ ] Add/remove/update a link to a theme
- [ ] Text cleanups/typo fixes

# Copyright Assignment

- [x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.

# Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/unixorn/awesome-zsh-plugins/blob/main/Contributing.md) document.
- [x] I have confirmed that the link(s) in my PR are valid.
- [x] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [ ] All new and existing tests passed.
- [ ] Any added completions have a readme and a license file in their repository.
- [x] Any added frameworks have a readme and a license file in their repository.
- [ ] Any added plugins have a readme and a license file in their repository.
- [ ] Any added themes have a screen shot, a readme and a license file in their repository.
- [xI have stripped leading and trailing **zsh-**, **zsh-plugin** and/or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name by preventing big clusters in the **O** and **Z** sections of the list.

### CODE REVIEW

**Comment by agkozak** [comment]
It looks as if [Narren Singh's](https://github.com/narrensingh) theme has disappeared from GitHub, and I cannot find it elsewhere. I'll be happy to remove it, if you like.

**Comment by unixorn** [comment]
Thanks, it'd be great if you removed the 404 theme as part of your PR

**Review by unixorn — CHANGES_REQUESTED** [review]
Go ahead and remove the 404 narren theme and I'll approve & merge, thanks!

**Comment by agkozak** [comment]
All taken care of. Thanks, Joe.

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
Thanks, I appreciate the contribution + the clean up

**Pull request merged**
