### PR TITLE
Add shellfirm plugin

### PR DESCRIPTION
**Pull request by kaplanelad**
# Description
New plugin for the list:) 
Shellfirm is a small plugin written in Rust that prompts you a double verification to your terminal when a risky command pattern is detected.

Visit in GitHub project to get more details 
https://github.com/kaplanelad/shellfirm

# Type of changes

- [ ] A link to an external resource like a blog post
- [ ] Add/remove/update a link to a framework
- [x] Add/remove/update a link to a plugin
- [ ] Add/remove/update a link to a tab completion
- [ ] Add/remove/update a link to a theme
- [ ] Text cleanups/typo fixes

# Copyright Assignment

- [x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.

# Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/unixorn/awesome-zsh-plugins/blob/main/Contributing.md) document.
- [ ] I have confirmed that the link(s) in my PR are valid.
- [ ] I have signed off my commits. You can use `git commit --amend --no-edit --signoff` to amend an existing commit, and you can find more details about signing off commits on the DCO GitHub action page [here](https://probot.github.io/apps/dco/)
- [ ] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [ ] All new and existing tests passed.
- [ ] Any added completions have a readme and a license file in their repository.
- [ ] Any added frameworks have a readme and a license file in their repository.
- [ ] Any added plugins have a readme and a license file in their repository.
- [ ] Any added themes have a screen shot, a readme and a license file in their repository.
- [ ] I have stripped leading and trailing **zsh-**, **zsh-plugin** and/or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name by preventing big clusters in the **O** and **Z** sections of the list.

### CODE REVIEW

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
One last thing - could you check the box that you're making the contribution under the BSD license terms?

**Comment by kaplanelad** [comment]
Hey @unixorn,
the project license is Apache-2.0 not good enough?

**Comment by unixorn** [comment]
Apache 2 for the project is fine, the box is for contributions to the list, which is BSD licensed. Sorry for the confusion.

**Comment by kaplanelad** [comment]
I marked the box (hope that I understand you correct)

**Comment by unixorn** [comment]
Thanks. I'll clarify it in the PR template.

**Pull request merged**
