### PR TITLE
Add oxide theme

### PR DESCRIPTION
**Pull request by dikiaap**
# Description

Add my oxide theme!

# Type of changes

- [ ] A link to an external resource like a blog post
- [ ] Add/remove a completion
- [ ] Add/remove a plugin
- [x] Add a theme
- [ ] Text cleanups/typo fixes

# Checklist:

- [x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.
- [x] I have confirmed that the link(s) in my PR are valid.
- [x] My entries are single lines and are in the appropriate (plugins, themes, completions) section.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.
- [x] I have stripped leading and trailing **zsh-** or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name since there aren't big clusters in the o and z sections of the list.

### CODE REVIEW

**Comment by dikiaap** [comment]
Travis CI says
```
Issues :-(
> Links 
  1. [L187] 503 http://tmux.sourceforge.net/
```

SourceForge is currently maintenance.

**Comment by unixorn** [comment]
Thanks for the contribution. I do have a suggestion, though - could you move it into its own repo and add a readme.md with a description of what extras it includes and a screen shot?

It's easier for people to decide if they want to use a theme when they can see what it looks like, and what features it adds.

**Comment by dikiaap** [comment]
There is actually a screenshot link in the [root repository](https://github.com/dikiaap/dotfiles#dotfiles--).

I just want to link to the source code because some people here do it too.
```
* [adlee](https://github.com/adlee-was-taken/oh-my-zsh-osx/blob/master/adlee.zsh-theme) - macOS theme, requires Powerline font.
* [af-magic-mod](https://raw.githubusercontent.com/desyncr/zshrc/master/themes/af-magic-mod.zsh-theme) - af-magic-mod theme. Install with `antigen theme desyncr/zshrc themes/af-magic-mod`.
* [gitster](https://github.com/shashankmehta/dotfiles/blob/master/thesetup/zsh/.oh-my-zsh/custom/themes/gitster.zsh-theme) - When in a git repo, it shows the location from the git's root folder. When not in a git repo, it shows the path relative to home, `~`.
* [feder](https://github.com/samfeder/feder.zsh-theme/blob/master/feder.zsh-theme) - Clean, simple, compatible and meaningful. Tested on Linux, Unix and Windows under ANSI colors.
etc
```

**Comment by dikiaap** [comment]
And I think that tmux website has been moved to https://tmux.github.io (https://github.com/tmux/tmux/wiki)

Old wiki: https://www.reddit.com/r/tmux/wiki/index?v=5d3e5db4-22f4-11e4-aea2-12313d148589
Current wiki: https://www.reddit.com/r/tmux/wiki/index

**Comment by unixorn** [comment]
Fair enough. I've come to think that its cleaner to have themes/plugins in their own repos instead of embedded in something else, but as you pointed out there are several others in the list doing the same thing.

**Pull request merged**
