### PR TITLE
Relocate miniplug to sr.ht

### PR DESCRIPTION
**Pull request by YerinAlexey**
# Description

Miniplug's canonical source code repository is on sourcehut: https://sr.ht/~yerinalexey/miniplug. The Github repository right now works as a mirror and may be deleted in the future.

# Type of changes

- [ ] A link to an external resource like a blog post
- [x] Add/remove/update a link to a framework
- [ ] Add/remove/update a link to a plugin
- [ ] Add/remove/update a link to a tab completion
- [ ] Add/remove/update a link to a theme
- [ ] Text cleanups/typo fixes

# Copyright Assignment

- [x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.

# Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have confirmed that the link(s) in my PR are valid.
- [x] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [ ] All new and existing tests passed.
- [x] Any added frameworks have a readme and a license file in their repository.

### CODE REVIEW

**Comment by unixorn** [comment]
Thanks for the update, I can use all the help I can get to keep up to date.

**Comment by YerinAlexey** [comment]
> I can use all the help I can get to keep up to date.

This PR is enough to keep miniplug up-to-date. Everything else looks good, and thanks for listing my project :)

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
Thanks for the contribution!

**Pull request merged**
