### PR TITLE
Add iterm2-shell-integration

### PR DESCRIPTION
**Pull request by decayofmind**
# Description

Some time ago I created a Zsh plugin to install iterm2 utilities. Now the author of iTerm2 moved those utilities and shell integration to a dedicated repository, naturally making my plugin not needed anymore.

# Type of changes

- [ ] A link to an external resource like a blog post
- [ ] Add/remove/update a link to a framework
- [x] Add/remove/update a link to a plugin
- [ ] Add/remove/update a link to a tab completion
- [ ] Add/remove/update a link to a theme
- [ ] Text cleanups/typo fixes

# Copyright Assignment

- [x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license. This is for the list submission, not for the project(s) you're adding, I don't care what license the plugins have as long as they have something.

# Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/unixorn/awesome-zsh-plugins/blob/main/Contributing.md) document.
- [ ] All new and existing tests passed.
- [x] I have confirmed that the link(s) in my PR is valid.
- [x] I have signed off my commits. You can use `git commit --amend --no-edit --signoff` to amend an existing commit, and you can find more details about signing off commits on the DCO GitHub action page [here](https://probot.github.io/apps/dco/).
- [x] My entries are single lines and are in the appropriate (plugins, themes, or completions) section, and in alphabetical order in their section.
- [ ] The completion/plugin/theme has a plugin file in the repository, it is not just bare instructions to be added to `.zshrc`
- [ ] Any added completions have a readme and a license file in their repository.
- [ ] Any added frameworks have a readme and a license file in their repository.
- [x] Any added plugins have a readme and a license file in their repository.
- [ ] Any added themes have a screenshot, a readme, and a license file in their repository.
- [x] I have stripped any leading and/or trailing **zsh-**, **zsh-plugin** and/or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name by preventing big clusters in the **O** and **Z** sections of the list.

### CODE REVIEW

**Comment by unixorn** [comment]
I don't see a plugin file in the repo - without one, ZSH frameworks can't automatically load it.

**Comment by decayofmind** [comment]
@unixorn So, should I just remove my plugin without adding a replacement, right?

**Comment by unixorn** [comment]
I added a plugin.zsh file in https://github.com/gnachman/iTerm2-shell-integration/pull/15

Once that's merged, ZSH frameworks will detect it and it will add the plugin's utilities directory to the user's `$PATH` automatically.

**Comment by decayofmind** [comment]
Amazing work @unixorn !

One small thing - It's not only binaries but also some helper functions to source under `shell_integration/zsh`, so the plugin file in PR needs one more line to add:

```sh
source "${0:h}/shell_integration/zsh"
```

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
Going to go ahead and merge this. If https://github.com/gnachman/iTerm2-shell-integration/pull/15 doesn't get closed in a reasonable amount of time, it might be worth updating your old plugin to load https://github.com/gnachman/iTerm2-shell-integration as a submodule and then its plugin file could add the utilities to `$PATH` and source the helper functions.

**Pull request merged**
