### PR TITLE
Update Znap info

### PR DESCRIPTION
**Pull request by marlonrichert**
# Description

Add a list of features.

# Type of changes

- [ ] A link to an external resource like a blog post
- [x] Add/remove a framework
- [ ] Add/remove a plugin
- [ ] Add/remove a tab completion
- [ ] Add/remove a theme
- [x] Text cleanups/typo fixes

# Copyright Assignment

- [x] This document is covered by the [BSD License](https://github.com/unixorn/awesome-zsh-plugins/blob/master/LICENSE), and I agree to contribute this PR under the terms of the license.

# Checklist:

- [ ] I have confirmed that the link(s) in my PR are valid.
- [ ] My entries are single lines and are in the appropriate (plugins, themes or completions) section, and in alphabetical order in their section.
- [x] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests passed.
- [ ] Any added completions have a license file in their repository.
- [ ] Any added plugins have a license file in their repository.
- [ ] Any added themes have a screen shot and a license file in their repository.
- [ ] I have stripped leading and trailing **zsh-** or **oh-my-zsh-** substrings from the link name. This makes it easier to find plugins/themes/completions by name since there aren't big clusters in the **O** and **Z** sections of the list.

### CODE REVIEW

**Comment by z0rc** [comment]
Can you please tone down use of italics? The document doesn't have them anywhere, and I believe there is no reason to introduce italics styling now.

**Comment by marlonrichert** [comment]
@z0rc Fixed.  I also removed the excessive use of **boldface** from Zinit's entry.

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
Thanks for the formatting cleanup

**Comment by marlonrichert** [comment]
@unixorn How would you feel about dropping the [Installation](https://github.com/unixorn/awesome-zsh-plugins#installation) section? It feels rather arbitrary what's included there. Plus, updating it to include install instruction for _all_ ZSH plugin managers and frameworks seems infeasible at this point.

**Comment by marlonrichert** [comment]
@unixorn Also, would you be open to me splitting the [Frameworks](https://github.com/unixorn/awesome-zsh-plugins#installation) section into two sections: "Frameworks" and "Plugin Managers"? To me, software like Antigen, Zinit & Znap are not frameworks; they are pure plugin managers. I consider only software that changes a lot of Zsh's default settings and come with pre-packaged plugins to be  frameworks, such as OMZ, Prezto & Zimfw. I think it would be very meaningful to distinguish between the two and list them separately.

**Comment by unixorn** [comment]
I'm pretty open to that. If we do split it, I'd want to make sure there are notes for the frameworks that can optionally pull in o-m-z. There's currently a setups section, too, should we think about merging into that?

**Comment by marlonrichert** [comment]
@unixorn I had a look and I think there’s not really meaningful distinction between a Zsh “setup” and a Zsh “framework”. Zsh “frameworks” are not _real_ frameworks in the narrow sense of the word anyway; you’re not going to use OMZ to build your next plugin. :) So yes, I agree with you that we should merge those.

Including notes on how to pull in OMZ (plus perhaps Prezto?) seems like a reasonable thing to do. Perhaps include some sample code. That would make it a lot easier to compare. But that’s also a lot more work. I think I’ll just start with splitting/merging plugins managers, frameworks and setups. Let’s how motivated I still am after that. ;)

**Comment by unixorn** [comment]
I think it is probably best to just say in the description that "this setup can pull in omz/prezto" and let them get the instructions how from the upstream.

If we try to include instructions here, then we're stuck having to maintain instructions for every framework whenever the upstream changes and that doesn't seem like a reasonable amount of work for the minimal return of saving someone from looking at the instructions for something they're using.

**Pull request merged**
